### ISSUE TITLE
Pass custom props/actions to child routers

### ISSUE THREAD

**Issue by auser** [t4t5/react-native-router#8]
It would be nice to be able to pass functions between parent views and child views. 

This is useful when showing a selection view so that after a selection is made, we can programmatically call another function.

**Comment by t4t5** [comment]
For passing custom data to your route you can use the `data` key in your route object. When pressing something in the view you can either call `this.props.toRoute(...)` to go directly to the next view or `this.props.customAction(...)` to call a custom action in your main view.

I think this should cover your needs. Otherwise feel free to reopen the issue. :-)

**Comment by auser** [comment]
I ended up passing a function through `props.data` and calling it directly. This works, but is not immediately apparent.

**Comment by boyswan** [comment]
auser would you be able to give an example of this? thanks
